### ISSUE TITLE
App_id and App_Secret

### ISSUE THREAD

**Issue by TheChrisTech** [ajmarks/sharkiq#2]
Hi @ajmarks , I see you've implemented a hardcoded app_id and app_secret.

`SHARK_APP_ID = "Shark-Android-field-id"
SHARK_APP_SECRET = "Shark-Android-field-Wv43MbdXRM297HUHotqe6lU1n-w"`

Can you tell me if these work for other users as well, or are these unique to you? How do you retrieve these for other users? I'm implementing something similar for Hubitat (Smart Hub), and while everything works for me, others are getting 403 Forbidden messages.

My Project: https://github.com/TheChrisTech/Hubitat-SharkIQRobot

**Comment by ajmarks** [comment]
They should apply to everybody unless Shark invalidates them.  They're both hardcoded in the Android app in `environment.smali`.

**Comment by TheChrisTech** [comment]
Figured that. They're just values for Shark to identify what app sent the request. So one could really "Spoof" what device it comes from. Thanks!
